repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ot-helm 
    url: https://ot-container-kit.github.io/helm-charts/

helmDefaults:
  kubeContext: kind-kind
  createNamespace: true
  historyMax: 3

releases:
  - name: ingress
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    values:
      - controller:
          resources: {}
          hostPort:
            enabled: true
          service:
            type: NodePort
            nodePorts:
              http: 32080
              https: 32443
          watchIngressWithoutClass: true
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - installCRDs: true
