---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDB
metadata:
  name: mongodb
spec:
  kubernetesConfig:
    image: quay.io/opstree/mongo:v5.0
    imagePullPolicy: IfNotPresent
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 10Gi
    storageClass: standard
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-secret
      key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  password: password