apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
spec:
  # redisConfig:
  #   additionalRedisConfig: redis-external-config
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    resources:
      requests: {}
      limits:
        cpu: 101m
        memory: 128Mi
  redisExporter:
    enabled: false
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  # nodeSelector:
  #   kubernetes.io/hostname: minikube
  # securityContext: {}
  # priorityClassName:
  # affinity:
  # Tolerations: []