apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: localhost.crt
spec:
  sources:
    - secret:
        name: root-secret
        key: ca.crt
  target:
    configMap:
      key: "ca.crt"